In [1]:
# Hopfield Network to store 4 vectors

import numpy as np

# -------- Training Patterns (4 vectors) --------
patterns = np.array([
    [1,  1,  1, -1],
    [1, -1,  1, -1],
    [-1, 1, -1, 1],
    [-1,-1, 1, 1]
])

# Number of neurons
n = patterns.shape[1]

# -------- Create Weight Matrix --------
W = np.zeros((n, n))

for p in patterns:
    W = W + np.outer(p, p)   # Outer product

# Diagonal should be zero
np.fill_diagonal(W, 0)

print("Weight Matrix:")
print(W)

# -------- Testing with Noisy Input --------
test = np.array([1, 1, -1, -1])

print("\nNoisy Input:")
print(test)

# -------- Recall Process --------
for i in range(5):   # iterate few times
    test = np.sign(np.dot(W, test))
    print("Iteration", i+1, ":", test)

print("\nRecovered Pattern:")
print(test)

Weight Matrix:
[[ 0.  0.  2. -4.]
 [ 0.  0. -2.  0.]
 [ 2. -2.  0. -2.]
 [-4.  0. -2.  0.]]

Noisy Input:
[ 1  1 -1 -1]
Iteration 1 : [ 1.  1.  1. -1.]
Iteration 2 : [ 1. -1.  1. -1.]
Iteration 3 : [ 1. -1.  1. -1.]
Iteration 4 : [ 1. -1.  1. -1.]
Iteration 5 : [ 1. -1.  1. -1.]

Recovered Pattern:
[ 1. -1.  1. -1.]
